# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "ホーム"
  url = "#about"
  weight =10

[[main]]
  name = "学会発表"
  url = "#talks"
  weight = 20

[[main]]
  name = "学術論文"
  url = "#publications"
  weight = 30

[[main]]
  name = "業績"
  url = "#accomplishments"
  weight = 40

[[main]]
  name = "職歴"
  url = "#experience" #"courses/"
  weight = 50

[[main]]
  name = "ブログ"
  url = "#posts"
  weight = 60

[[main]]
  name = "連絡先"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
